### ISSUE TITLE
Add a proposal-url to proposal-trait

### ISSUE THREAD

**Issue by mijoco-btc** [Clarity-Innovation-Lab/executor-dao#7]
Proposal trait of the reference implementation of Executor DAO should provide a getter to an optional proposal meta data url. The motivation for this is to enable/encourage turnout by making the proposal transparent and open to all community members.
 
The reference implementation would simply provide an empty getter. Beyond this, implementation could follow the generally accepted pattern for token-uri in NFT contracts - e.g. with a setter that can be frozen at start block height and proposal meta-data stored in content addressable storage. 

e.g. trait..

```
(get-proposal-uri (uint) (response (optional (string-ascii 256)) uint))
```

contract..

```
(define-read-only (get-proposal-uri (id uint)) (ok (some (var-get proposal-uri))))
```

**Comment by MarvinJanssen** [comment]
I vote against this initially, but open to be persuaded. My main question is: what kind of information has to live off-chain to warrant off-chain metadata?

Counterpoints:

- Off-chain metadata is subject to link rot. The metadata might at some point disappear and then information is lost. All data inside the contract will remain for as long as Stacks exists.
- A textual description can (and in my opinion should) exist in the contract itself as comments or a string type. The formatted comments at the top of the reference proposals is meant to eventually be interpreted by a frontend and then displayed. The Clarity code can be fetched just as easily as any external metadata file. (But of course no system does it right now and there is no formal specification so the structure itself is open to debate.)
- Having all information inside the contract makes it self-contained.

```clarity
;; Title: EDP001 Dev Fund
;; Author: Marvin Janssen
;; Synopsis:
;; This proposal creates a simple dev fund that pays developers on a monthly basis.
;; Description:
;; If this proposal passes, it mints new governance tokens equal to 30% of the total
;; supply and awards them to the EDE005 Dev Fund extension. It contains a number of
;; principals and set allowances. Any principal with an allowance is able to claim
;; an amount of tokens equal to the allowance on a (roughly) monthly basis.
;; Principals can be added and removed, and allowances can be changed via future
;; proposals.
```

**Comment by mijoco-btc** [comment]
Ok here goes 😉 

I think it's a question of perspective. The DAO can be used for the on-chain use cases, evolving its protocol, paying developers/contributors etc but it can also be a really important tool for decision making and engagement. 

For example - the outcome of a vote could be a criteria in the mix of the activation criteria for a SIP - effectively giving the community a veto over adoption of a SIP - likewise for SF grants. In this case the proposal would simply print the result of the vote. There'd be no on-chain state outside of the voting data itself. 

Rather than storing proposal data in Github/centralised db we can do better by following the best practice from NFTs and use IPFS plus the locking/freezing of the URL before voting begins. 

From this perspective a proposal at its most general could be a batch of multi media files designed to provide context for the voting.

**Comment by MarvinJanssen** [comment]
You could put markdown in a Clarity contract if you so desire. If the vote is merely to signal sentiment, then you can also do something like this:

```clarity
;; Title: EDPXXX SIP Activation Criteria for SIPXXX
;; Author: Marvin Janssen
;; Synopsis:
;; Proposes the SIP Activation Criteria for SIPXXX to be XYZ.
;; Description:
;; This proposal is part of the ongoing discussion at [link] to
;; vote on the activation criteria for SIPXXX.
;; [background info]
;; This proposal is to vote for Option A as described above.

(impl-trait .proposal-trait.proposal-trait)

(define-public (execute (sender principal))
	(begin
		(print "Option A")
		(ok true)
	)
)
```

The `print` is technically not even needed because proposal voting contract will also emit an event: `{event: "conclude", proposal: SP..., passed: true/false}`

>Rather than storing proposal data in Github/centralised db we can do better by following the best practice from NFTs and use IPFS plus the locking/freezing of the URL before voting begins.

It is definitely "common practice" but does that make it "best practice"? I guess it is the best we have but if we can put critical information on-chain then why not do it? And for those that do not like blockchain stuffing we could always put a hash of the proposal document on-chain in the proposal contract.

**Comment by mijoco-btc** [comment]
Am not disagreeing with putting critical data on chain.

`we could always put a hash of the proposal document on-chain in the proposal contract`

this is what this is proposal is proposing we optionally can store a hash to content addressed storage.

**Comment by MarvinJanssen** [comment]
Why do we need a read-only function for it?

**Comment by mijoco-btc** [comment]
for ui integration - was thinking this way (using the freeze meta data approach) we decouple the off chain data from the contract deployment - the off chain data needs to be frozen by the time voting starts. More flexible. But i see your concern in that introduces more moving parts.

**Comment by LNow** [comment]
I'd say that this function can be added to proposals, but it doesn't have to be part of `proposal-trait`. Just like `claim` is not part of SIP-009, or `mint` is not part of SIP-010.

I don't think proposals will require wallets support, nor that we'll see dozens of different UI's that support executor dao (I hope I'm wrong with the last one). And because of that keeping list of required functions to bare minimum seems like a good idea

**Comment by MarvinJanssen** [comment]
Agreed. Since the frontend is specific for eDAO it can be made display whatever we want.

**Comment by mijoco-btc** [comment]
Ok - will close this issue here and move it to the new EcosystemDAO repo thats just been forked from here.

In EcosystemDAO the proposal-trait will remain as is - the UI will handle both cases (proposal-url exists/ not exists) and provide guidance on how to write the proposal if the author wants to include off-chain meta data.

**Comment by Hero-Gamer** [comment]
Interesting discussion. :) I look forward to understanding this more and help where I can.  :)

My primary interest would be to have improvement on SIP voting procedure than Stacks 2.05 vote.

**Comment by whoabuddy** [comment]
Adding my little bit here - with CityCoins governance we tied the off-chain component on GitHub to the vote using commit hashes:

https://github.com/citycoins/contracts/blob/ebdef00122e9b6c2912ceeae560f7f7c1b707e35/contracts/Vote/citycoins-vote-v1-mainnet.clar#L35-L53

I agree this doesn't need to be part of the trait, and I'm curious if Gaia would be a good solution here - e.g. [Stacks White Paper](https://gaia.blockstack.org/hub/1AxyPunHHAHiEffXWESKfbvmBpGQv138Fp/stacks.pdf)

**Comment by mijoco-btc** [comment]
Thats a nice solution - thank you!

I'll close this here - please [go here for open discussions](https://github.com/Clarity-Innovation-Lab/ecosystem-dao/issues) on EcosystemDAO
